% Compile AML2Lucretia mex file

% Set Paths UAP and XERCES:
% (you also need to set your LD_LIBRARY_PATH to include $XERCESROOT/lib)
% XERCESROOT='/u/ey/whitegr/u01/whitegr/xerces-c-src_2_8_0';
% UAPROOT='/u/ey/whitegr/u01/whitegr/accelerator-ml/uap/trunk';
XERCESROOT='/home/smolloy/Documents/xerces-c-src_2_8_0';
UAPROOT='/home/smolloy/Documents/accelerator-ml/uap/trunk';


mex('-v', ...
    ['-L',UAPROOT,'/lib -lantlr -luap'], ...
    ['-L',XERCESROOT,'/lib -lxerces-c'], ...
    ['-I',XERCESROOT,'/include'], ...
    ['-I',UAPROOT,'/ANTLR270/antlr'], ...
    ['-I',UAPROOT,'/ANTLR270'], ...
    ['-I',UAPROOT], ...
    'testing.cpp', ...
    'UAPNode2Lucretia.cpp', ...
    'make_beambeam.cpp', 'make_drift.cpp', 'make_marker.cpp', 'make_oct.cpp', 'make_rfcav.cpp', 'make_taylor.cpp', ...
    'make_bend.cpp', 'make_electrickicker.cpp', 'make_match.cpp', 'make_patch.cpp', 'make_sext.cpp', ...
    'make_thinmult.cpp', 'make_custom.cpp', 'make_kicker.cpp', 'make_mult.cpp', 'make_quad.cpp', ...
    'make_solenoid.cpp', 'make_wiggler.cpp', 'make_magnet.cpp', 'getUAPinfo.cpp', ...
    [UAPROOT,'/ANTLR270/Parser.o'], ...
    [UAPROOT,'/ANTLR270/CharScanner.o'], ...
    [UAPROOT,'/ANTLR270/TreeParser.o'], ...
    [UAPROOT,'/ANTLR270/LLkParser.o'], ...
    [UAPROOT,'/ANTLR270/NoViableAltForCharException.o'], ...
    [UAPROOT,'/ANTLR270/NoViableAltException.o'])

disp('Done')
