function AddBPMsToQuadBlocks()
%
% The EXT BPMs are physically attached to their parent quadrupoles, but in
% the MAD deck they are a short distance (6 cm) away ... add each BPM to it's
% parent quadrupole's block

global BEAMLINE

BlockNames=[ ...
  {'ML1X'}, {'QF1X'}; ...
  {'ML2X'}, {'QD2X'}; ...
  {'ML3X'}, {'QF3X'}; ...
  {'ML4X'}, {'QF4X'}; ...
  {'ML5X'}, {'QD5X'}; ...
  {'ML6X'}, {'QF6X'}; ...
  {'ML7X'}, {'QF7X'}; ...
  {'ML8X'}, {'QD8X'}; ...
  {'ML9X'}, {'QF9X'}; ...
  {'ML10X'},{'QD10X'}; ...
  {'ML11X'},{'QF11X'}; ...
  {'ML12X'},{'QD12X'}; ...
  {'ML13X'},{'QF13X'}; ...
  {'ML14X'},{'QD14X'}; ...
  {'ML15X'},{'QF15X'}; ...
  {'ML16X'},{'QD16X'}; ...
  {'ML17X'},{'QF17X'}; ...
  {'MQ18X'},{'QD18X'}; ...
  {'MQ19X'},{'QF19X'}; ...
  {'MQ20X'},{'QD20X'}; ...
  {'MQ21X'},{'QF21X'}; ...
];

for n=1:length(BlockNames)
  idm=findcells(BEAMLINE,'Name',BlockNames{n,1});
  idq=findcells(BEAMLINE,'Name',BlockNames{n,2});
  Block0=BEAMLINE{idq(1)}.Block;
  Block=[min(idm,Block0(1)),max(idm,Block0(2))];
  BEAMLINE{idm}.Block=Block;
  id=findcells(BEAMLINE,'Block',Block0);
  for m=id
    BEAMLINE{m}.Block=Block;
  end
end

% fix some incorrect block assignments

id=findcells(BEAMLINE,'Name','ZHSIM1');
BEAMLINE{id}=rmfield(BEAMLINE{id},'Block');
id=findcells(BEAMLINE,'Name','ZVSIM1');
BEAMLINE{id}=rmfield(BEAMLINE{id},'Block');
id=findcells(BEAMLINE,'Name','QM16');
for n=id,BEAMLINE{n}.Block=id;end

return
