function multi_knob_ip


format long;


factor_qd0=[];
factor_qf1=[];
factor_qf9b=[];
N_PS_iqd0=[];
N_PS_iqf1=[];
N_PS_iqf9b=[];


%CREATING THE DATA

   mOutputArgs={};

     kl_qd0_design=-1.112672023613;
    kl_qf1_design=0.702138653141;
    kl_qf9b_design=0.378649967733;
    
    

%CREATING GUI AND ITS COMPONENTS

%  The main figure for GUI

   hMainFigure = figure(...       % The main GUI figure
                    'MenuBar','none', ...
                    'Toolbar','none', ...
                    'HandleVisibility','callback', ...
                    'Name','Wire scanner',...
                    'Color', get(0,...
                             'defaultuicontrolbackgroundcolor'));



%The edit button for alpha x               

hAlfaxText = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.05 0.9 0.11 0.05],...
                   'FontSize',16,...
                   'String','delta alphax',...
                   'BackgroundColor','white',...
                   'Style','text');
               
hAlfaxEdit = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.17 0.9 0.11 0.05],...
                   'FontSize',16,...
                   'String','0',...
                   'Style','edit');  
              
                         
                         
%The edit button for alpha y               

hAlfayText = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.05 0.82 0.11 0.05],...
                   'FontSize',16,...
                   'String','delta alphay',...
                   'BackgroundColor','white',...
                   'Style','text');
               
hAlfayEdit = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.17 0.82 0.11 0.05],...
                   'FontSize',16,...
                   'String','0',...
                   'Style','edit');  


%The edit button for Dx               

hDispxText = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.05 0.74 0.11 0.05],...
                   'FontSize',16,...
                   'String','delta Dx',...
                   'BackgroundColor','white',...
                   'Style','text');
               
hDispxEdit = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.17 0.74 0.11 0.05],...
                   'FontSize',16,...
                   'String','0',...
                   'Style','edit');      
               

               
               
%The edit button for QD0FF strenght               

hQD0FFText = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.35 0.9 0.11 0.05],...
                   'FontSize',16,...
                   'String','factor QD0FF',...
                   'BackgroundColor','white',...
                   'Style','text');
               
               
hQD0FFText2 = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.47 0.9 0.11 0.05],...
                   'FontSize',16,...
                   'BackgroundColor','white',...
                   'Style','text');
               
               

%The edit button for QF1FF strenght               

hQF1FFText = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.35 0.82 0.11 0.05],...
                   'FontSize',16,...
                   'String','factor QF1FF',...
                   'BackgroundColor','white',...
                   'Style','text');
               
               
hQF1FFText2 = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.47 0.82 0.11 0.05],...
                   'FontSize',16,...
                   'BackgroundColor','white',...
                   'Style','text');
               
               
               
%The edit button for QF9BFF strenght               

hQF9BFFText = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.35 0.74 0.11 0.05],...
                   'FontSize',16,...
                   'String','factor QF9BFF',...
                   'BackgroundColor','white',...
                   'Style','text');
               
               
hQF9BFFText2 = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.47 0.74 0.11 0.05],...
                   'FontSize',16,...
                   'BackgroundColor','white',...
                   'Style','text');               
               
               
               
%The run button

hRunButton = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.4 0.5 0.11 0.05],...
                   'FontSize',16,...
                   'String','Run',...
                   'Style','pushbutton',...
                   'Callback', @hRunButtonCallback);


%The write button

hWriteButton = uicontrol(... % Button for updating selected plot
                   'Parent', hMainFigure, ...
                   'Units','normalized',...
                   'HandleVisibility','callback', ...
                   'Position',[0.6 0.5 0.11 0.05],...
                   'FontSize',16,...
                   'String','Write',...
                   'Style','pushbutton',...
                   'Callback', @hWriteButtonCallback);
               


 function hRunButtonCallback(hObject, eventdata) 
      
   
global BEAMLINE PS Ampl0_qd0 Ampl0_qf1 Ampl0_qf9b

 delta_alpha_x=str2double(get(hAlfaxEdit, 'String'));
 delta_alpha_y=str2double(get(hAlfayEdit, 'String'));
 delta_dispx=str2double(get(hDispxEdit, 'String'));
 matrice=[0.001124917651000 -1.265874789999621e-004 -0.005780308823000; 8.486649810000024e-004 -9.585961600000470e-005 4.963293999959983e-006; 9.786080000018238e-005 2.675123490000209e-004 -9.001343690000496e-004];
 %matrice=[0.001101396944000 -9.045866299994820e-005 -0.005791390091000; 8.299689819999401e-004 -6.815617199995572e-005 4.012200000014232e-008; 1.059999360000230e-004 3.046398800000683e-004 -0.001006896081000];
 delta_klqd0=matrice(1,1)*delta_alpha_x+matrice(2,1)*delta_alpha_y+matrice(3,1)*delta_dispx;
 delta_klqf1=matrice(1,2)*delta_alpha_x+matrice(2,2)*delta_alpha_y+matrice(3,2)*delta_dispx;
 delta_klqf9b=matrice(1,3)*delta_alpha_x+matrice(2,3)*delta_alpha_y+matrice(3,3)*delta_dispx;
  
 
 
%  %read kl qd0ff   
iqd0=findcells(BEAMLINE,'Name','QD0FF');
% tesla_qd0_current=BEAMLINE{iqd0(1,1)}.B*2;
N_PS_iqd0=BEAMLINE{iqd0(1,1)}.PS;
Ampl0_qd0=PS(N_PS_iqd0).Ampl;
% 
% %read kl qf1ff  
iqf1=findcells(BEAMLINE,'Name','QF1FF');
% tesla_qf1_current=BEAMLINE{iqf1(1,1)}.B*2;
N_PS_iqf1=BEAMLINE{iqf1(1,1)}.PS;
Ampl0_qf1=PS(N_PS_iqf1).Ampl;
% 
% %read klqf9bff
iqf9b=findcells(BEAMLINE,'Name','QF9BFF');
% tesla_qf9b_current=BEAMLINE{iqf9b(1,1)}.B*2;
N_PS_iqf9b=BEAMLINE{iqf9b(1,1)}.PS;
Ampl0_qf9b=PS(N_PS_iqf9b).Ampl;

%factor
factor_qd0=1+delta_klqd0/kl_qd0_design;
factor_qf1=1+delta_klqf1/kl_qf1_design;
factor_qf9b=1+delta_klqf9b/kl_qf9b_design;



%output du gui
set(hQD0FFText2,'String',num2str(factor_qd0,'%g')); 
set(hQF1FFText2,'String',num2str(factor_qf1,'%g')); 
set(hQF9BFFText2,'String',num2str(factor_qf9b,'%g'));


 end
 



function hWriteButtonCallback(hObject, eventdata) 
    
global PS Ampl0_qd0 Ampl0_qf1 Ampl0_qf9b

PS(N_PS_iqd0).SetPt=factor_qd0*Ampl0_qd0;
[stat,I]=PSTrim(N_PS_iqd0,1);

PS(N_PS_iqf1).SetPt=factor_qf1*Ampl0_qf1;
[stat,I]=PSTrim(N_PS_iqf1,1);

PS(N_PS_iqf9b).SetPt=factor_qf9b*Ampl0_qf9b;
[stat,I]=PSTrim(N_PS_iqf9b,1);

end
 



               

end